(() => {
    const aliasToSlug = {
        // CMS / e-commerce
        wordpress: 'wordpress',
        woocommerce: 'woocommerce',
        shopify: 'shopify',
        drupal: 'drupal',
        prestashop: 'prestashop',
        magento: 'magento',
        joomla: 'joomla',
        ghost: 'ghost',
        webflow: 'webflow',
        wix: 'wix',
        squarespace: 'squarespace',
        strapi: 'strapi',
        contentful: 'contentful',
        sanity: 'sanity',

        // SEO / WP plugins
        elementor: 'elementor',
        rankmath: 'rankmath',
        rankmathseo: 'rankmath',
        yoast: 'yoast',
        seopress: 'seopress',

        // JS frameworks
        react: 'react',
        reactjs: 'react',
        preact: 'preact',
        next: 'nextjs',
        nextjs: 'nextjs',
        nuxt: 'nuxtjs',
        nuxtjs: 'nuxtjs',
        vue: 'vuejs',
        vuejs: 'vuejs',
        angular: 'angularjs',
        angularjs: 'angularjs',
        svelte: 'svelte',
        sveltekit: 'svelte',
        solid: 'solidjs',
        solidjs: 'solidjs',
        qwik: 'qwik',
        astro: 'astro',
        remix: 'remix',
        gatsby: 'gatsby',
        ember: 'ember',
        backbone: 'backbonejs',

        // CSS / UI
        bootstrap: 'bootstrap',
        tailwind: 'tailwindcss',
        tailwindcss: 'tailwindcss',
        bulma: 'bulma',
        foundation: 'foundation',
        mui: 'materialui',
        materialui: 'materialui',
        material: 'materialui',
        chakra: 'chakraui',
        chakraui: 'chakraui',
        antd: 'antdesign',
        antdesign: 'antdesign',
        sass: 'sass',
        less: 'less',

        // JS runtimes / build tools
        node: 'nodejs',
        nodejs: 'nodejs',
        deno: 'denojs',
        bun: 'bun',
        webpack: 'webpack',
        vite: 'vitejs',
        parcel: 'parcel',
        rollup: 'rollupjs',
        babel: 'babel',
        esbuild: 'esbuild',
        swc: 'swc',

        // JS libs
        jquery: 'jquery',
        lodash: 'lodash',
        rxjs: 'rxjs',
        d3: 'd3js',
        three: 'threejs',
        threejs: 'threejs',
        chartjs: 'chartjs',
        animejs: 'animejs',
        gsap: 'greensock',

        // Languages
        javascript: 'javascript',
        js: 'javascript',
        typescript: 'typescript',
        ts: 'typescript',
        python: 'python',
        php: 'php',
        ruby: 'ruby',
        java: 'java',
        kotlin: 'kotlin',
        scala: 'scala',
        csharp: 'csharp',
        dotnet: 'dot-net',
        go: 'go',
        rust: 'rust',
        swift: 'swift',
        dart: 'dart',
        elixir: 'elixir',
        haskell: 'haskell',
        clojure: 'clojure',

        // Backend frameworks
        laravel: 'laravel',
        symfony: 'symfony',
        codeigniter: 'codeigniter',
        yii: 'yii',
        cakephp: 'cakephp',
        django: 'django',
        flask: 'flask',
        fastapi: 'fastapi',
        rails: 'rails',
        rubyonrails: 'rails',
        spring: 'spring',
        springboot: 'spring',
        express: 'express',
        nest: 'nestjs',
        nestjs: 'nestjs',
        koa: 'koa',

        // Databases / cache
        mysql: 'mysql',
        mariadb: 'mariadb',
        postgresql: 'postgresql',
        postgres: 'postgresql',
        mongodb: 'mongodb',
        redis: 'redis',
        sqlite: 'sqlite',
        elasticsearch: 'elasticsearch',

        // Cloud / infra / tools
        docker: 'docker',
        kubernetes: 'kubernetes',
        nginx: 'nginx',
        apache: 'apache',
        firebase: 'firebase',
        vercel: 'vercel',
        netlify: 'netlify',
        cloudflare: 'cloudflare',
        aws: 'amazonwebservices',
        gcp: 'googlecloud',
        azure: 'azure',
        github: 'github',
        gitlab: 'gitlab',

        // Analytics / tracking / tags
        googleanalytics: 'googleanalytics',
        gtag: 'googleanalytics',
        googletagmanager: 'google-tag-manager',
        gtm: 'google-tag-manager',
        hotjar: 'hotjar',
        matomo: 'matomo',
        segment: 'segment',
        plausible: 'plausible',

        // Common services / CDNs seen in script URLs
        cloudinary: 'cloudinary',
        algolia: 'algolia',
        stripe: 'stripe',
        sentry: 'sentry',
        intercom: 'intercom',
        hubspot: 'hubspot',
        npm: 'npm',
        yarn: 'yarn'
    };

    globalThis.TechLogoAliasesV2 = Object.freeze(aliasToSlug);
})();
